export const LIVE_MATCH_DATA = {
    totalRuns : 0,
    wicketCount : 0,
    totalOvers: 0,
    crr:0,
    currentRunStack:[],
    team_1 : '',
    team_2:'',
    maxOver:'',
    batting:'',
    scoring_team:'',
    chessing_team:'',
    tossWon:'',
    electedTo:'',
    STRIKER:'',
    NSTRIKER:'',
    batter1:{},
    batter2:{},
    CBOWLER:'',
    CBOWLER_ID : '',
    bowler : {},
    bowlers:[],
    currentBowlerData : {},
    recentOvers:[],
    extras:{},
    match:{},
    teamA:[],
    teamB:[],
    strikerFlag : false,
    batters:[],
    inningNo:1,
    showModalScorecard : false,
    match_id : 0,
    showModalTeamSelect:true,
    showModalMatchSetup:false,
    showModalSelectBatter:false,
    showModalSelectNS:false,
    showModalSelectBowler:false,
    ground_id:'',
    place_id:'',
    tour_id:'',
    matchStatus:'',
    showModalEndInnings : false,
    fielderArray : []
   


}